DROP TABLE IF EXISTS deptartment;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee;



CREATE TABLE department (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  salary DECIMAL NOT NULL,
  dept_id INTEGER,
  CONSTRAINT fk_departments 
  FOREIGN KEY (dept_id) 
  REFERENCES department(id) ON DELETE SET NULL
);

CREATE TABLE employee (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER,
  manager_id INTEGER,
  CONSTRAINT fk_roles 
  FOREIGN KEY (role_id) 
  REFERENCES role(id) ON DELETE SET NULL,

  CONSTRAINT fk_manager 
  FOREIGN KEY (manager_id) 
  REFERENCES employee(id) ON DELETE SET NULL
);



